export const pinturas = [
  { normal: "13.jpg", tiny: "tinified/13.jpg" },
  { normal: "23.jpg", tiny: "tinified/23.jpg" },
  { normal: "11.jpg", tiny: "tinified/11.jpg" },
  { normal: "4.jpg", tiny: "tinified/4.jpg" },
  { normal: "24.jpg", tiny: "tinified/24.jpg" },
  { normal: "2.jpg", tiny: "tinified/2.jpg" },
  { normal: "3.jpg", tiny: "tinified/3.jpg" },
  { normal: "1.jpg", tiny: "tinified/1.jpg" },
  { normal: "6.jpg", tiny: "tinified/6.jpg" },
  { normal: "5.jpg", tiny: "tinified/5.jpg" },
  { normal: "7.jpg", tiny: "tinified/7.jpg" },
  { normal: "8.jpg", tiny: "tinified/8.jpg" },
  { normal: "9.jpg", tiny: "tinified/9.jpg" },
  { normal: "10.jpg", tiny: "tinified/10.jpg" },
  { normal: "12.jpg", tiny: "tinified/12.jpg" },
  { normal: "14.jpg", tiny: "tinified/14.jpg" },
  { normal: "15.jpg", tiny: "tinified/15.jpg" },
  { normal: "16.jpg", tiny: "tinified/16.jpg" },
  { normal: "20.jpg", tiny: "tinified/20.jpg" },
  { normal: "17.jpg", tiny: "tinified/17.jpg" },
  { normal: "18.jpg", tiny: "tinified/18.jpg" },
  { normal: "19.jpg", tiny: "tinified/19.jpg" },
  { normal: "21.jpg", tiny: "tinified/21.jpg" },
  { normal: "22.jpg", tiny: "tinified/22.jpg" },
  { normal: "25.jpg", tiny: "tinified/25.jpg" },
];
